---
title: "ESSD fortedata manuscript"
output: html_document
author: Jeff Atkins
date: "`r format(Sys.time(), '%d %B %Y')`"
---

This document is intended to be the core of the planned ESSD manuscript: summarizing the database, giving stats, describing datasets, etc.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(fortedata)
library(dplyr)
library(lubridate)
library(readr)
library(tidyr)

# Metadata file
mdf <- system.file("extdata", "forte_table_metadata.csv", 
                   package = "fortedata", 
                   mustWork = TRUE)
md <- read.csv(mdf, stringsAsFactors = FALSE)
```

As of this writing (`r Sys.Date()`) the current version of `fortedata` is `r packageVersion("fortedata")`.

### Structure


### Plots table

```{r table_plots}
options(knitr.kable.NA = "")
make_table <- function(metadata, table_name) {
  metadata %>% 
    filter(Table == table_name) %>%
    select(-Table, -Notes) %>% 
#    arrange(Field) %>% 
    kableExtra::kable(format = "markdown")
}
make_table(md, "fd_plots")
```

### Subplots table

```{r table_subplots}
make_table(md, "fd_subplots")
```

### Nested subplots table

```{r table_nested_subplots}
make_table(md, "fd_nested_subplots")
```

### Inventory dataset

```{r table_contributors}
make_table(md, "fd_inventory")
```
